dwyl/learn-tdd

README.md
tidy readme based on comments/suggestions given at Ladies Who Code event.
see: https://github.com/ladieswhocode/london/tree/master/meetups/2015-june
=> initial tidy of readme

.gitignore, .travis.yml, README.md, change.js, index.html, package.json, static-server.js, test.js
+ removes 'use strict'; from change.js https://github.com/nelsonic/learn-tdd/issues/1 
+ adds jsdoc documentation explaining the function. see: https://github.com/docdis/learn-jsdoc'
=> tidy up ready for release

README.md
@nelsonic Resolving issue #18 :+1:
=> Fixes minor typos and adds clarifications

README.md, package.json
Totes forgot about this... #FoundTheNextShinyThing :wink: 
Please review/merge and ***Tweet*** https://github.com/dwyl/learn-tdd/issues/17
_thanks_!
=> Transfer repo to dwyl

README.md
Change misspelled word to 'templates'.
=> Micro typo

README.md
As discussed in: https://github.com/dwyl/learn-tdd/pull/25
=> Updated the getChange function

package.json
fixes https://githubcom/dwyl/learn-tdd/issues/27
=> updates Hapi to latest no code changes required

README.md
=> how to install atom command to terminal

package.json
As the name suggests. micro-update. thanks.
=> update to latest hapi, istanbul and nodemon

.travis.yml, README.md, package.json
Self explanatory... https://github.com/dwyl/learn-tdd/issues/39
=> Migrate to codecov

README.md
Fixed some typos and minor text glitches :smile:
=> fixed various typos

package.json
Fixes https://github.com/dwyl/learn-tdd/issues/45
No code changed.
Please merge. thanks.
=> update version of Hapi.js to latest (12.1.0)

.travis.yml, change.js, index.html, package.json, test.js
#47 took me a while but got there in the end! Reverted changes back to last commit and updated Istanbul to latest version.
=> Revert changes

README.md
Thanks for your tutorial.
I hava read the tdd tutorial just now. When I execute bonus 2 code, nothing happened. After comparing the **change.js** in the root directory. I found the tutorial about bonus 2 missed something which would run the test.
=> add code for bonus 2

test.js
=> Fixed typo 2

package.json
fixes https://github.com/dwyl/learn-tdd/issues/53
@iteles  please merge when you can. thanks. 👍
=> update devDependencies to latest versions. 

.travis.yml, README.md, package.json
PR details:
- f5b67a2 : Some improvements like concepts and resources added to `README.md`.
- e567f02 : Added latest node versions (v5 and v6) to `.travis.yml`.
- 8e05b81 : Minor `README.md` fixes.
- e2b7287 : `package.json` updated to `v1.0.7`
=> Some concepts and latest node versions (travis) added

README.md
Replaced unreliable Ferrari pit crew image with reliable Mercedes pit crew image, in order to better convey the spirit of TDD.
(This is the last time I create an issue to crack a bad joke.)
=> Replace image

README.md
=> Just a small typo

CONTRIBUTING.md
Adds CONTRIBUTING.md file pointing to https://github.com/dwyl/contributing :heart: :white_check_mark: fixes https://github.com/dwyl/learn-tdd/issues/74
=> Adds contributing guide

README.md
I've added a short instruction to make sure to tick the "Enable Coverage" button.
Relates to #82
=> Add "Enable Coverage" instruction

README.md
Added npm init -f
Create a minimal package.json with defaults
Works fine in Ubuntu 14.04 with Node v6.10.2
=> Create package.json Live Server install (#69)

README.md
Suggestion for a more user-friendly requirement.
I hope it fits the proposal.
#68
=> focus on "user story" as your requirement(s) #68

README.md
Removes word duplicate from the readme.md
=> Removes word duplicate

.travis.yml, README.md, change-functional.js, change.js, index.html, test.js
Adds solution to the `getChange` following _functional_ JS. for #109  👍
=> Functional solution issue#109

README.md
To run jsdoc commnad  on windows this change is necessary
=> Change jsdoc command

README.md
Adds a link to completed TodoMVC TDD example by @nelsonic that can be found here https://github.com/dwyl/todomvc-vanilla-javascript-elm-architecture-example
[#116](https://github.com/dwyl/learn-tdd/issues/116)
=> Add Link to TodoMVC TDD Example

README.md
+ [x] Reduce "what should I learn next?" section to de-clutter and help readers focus.
+ [x] Tidy up line length for maintainability.
+ [x] Fixed a couple of typos.
=> Reduce Learn Next Section issue #118

README.md
=> fix: fix spelling for "principles"

.github/dependabot.yml
+ [x] Create `dependabot.yml` file fixes issue #146
=> PR: Create dependabot.yml file fixes issue #146

README.md
From: [![GitHub Workflow Status](https://img.shields.io/github/workflow/status/dwyl/learn-tdd/Node.js%20CI?style=flat-square)](https://github.com/dwyl/learn-tdd/actions) to: [![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/dwyl/learn-tdd/ci.yml?label=build&style=flat-square&branch=main)](https://github.com/dwyl/learn-tdd/actions/workflows/ci.yml)
=> PR: Fix build badge in README.md
